# -*- coding: utf-8 -*-
"""RAG - Students Example - 1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qaVsdXC8Ny7V87SakL-nxiDFcaQlOFQK

# Day 4 — Practical RAG: Enterprise HR Knowledge Assistant

## Student Notebook — FREE Google Colab

We will build the syllabus project step by step:

**PDFs → Text → Chunks → Metadata → Embeddings → Vector Database → Similarity Search → Semantic Search → RAG → Answer → Citations → Multi-document Search → Evaluation**

No OpenAI API credits are required.

## How to use this notebook

For each stage:

**1. Understand the concept → 2. Run the code → 3. Observe the result → 4. Move to the next stage.**

The application is the practical demonstration of every syllabus topic.

# 1. Install the required libraries

- `pypdf` → PDF text extraction
- `sentence-transformers` → free local embeddings
- `chromadb` → local vector database
- `transformers` → local LLM
- `accelerate` → model runtime

No paid API is needed.
"""

!pip install -q pypdf sentence-transformers chromadb transformers accelerate
print("✅ Installation complete")

"""# 2. Upload HR Policy PDFs

Upload one or more PDFs, for example:

- Leave and Holiday Policy
- Work From Home Policy
- Employee Handbook
- Travel Policy

Multiple PDFs let us demonstrate **multi-document search**.
"""

from google.colab import files

uploaded_files = files.upload()

print(f"✅ Uploaded {len(uploaded_files)} file(s)")
for filename in uploaded_files:
    print(" -", filename)

"""# 3. PDF → Text

First we extract text from every PDF page.

We also keep **metadata**:

- `source` = PDF filename
- `page` = page number

This metadata will later be used for citations.
"""

!pip install -q pypdf
from pypdf import PdfReader

documents = []

for filename in uploaded_files:
    reader = PdfReader(filename)

    for page_number, page in enumerate(reader.pages, start=1):
        text = page.extract_text()

        if text and text.strip():
            documents.append({
                "text": text.strip(),
                "source": filename,
                "page": page_number
            })

print("✅ Text extraction complete")
print("Pages extracted:", len(documents))

for doc in documents[:2]:
    print("\nSOURCE:", doc["source"])
    print("PAGE:", doc["page"])
    print("TEXT PREVIEW:", doc["text"][:500])

"""# 4. Chunking

### Why chunk?

A large PDF may contain thousands of words. We divide it into smaller searchable pieces called **chunks**.

For this classroom lab:

- Chunk size = 500 words
- Overlap = 50 words

Each chunk keeps its `source` and `page` metadata.
"""

CHUNK_SIZE = 500
CHUNK_OVERLAP = 50

chunks = []
chunk_id = 0

for document in documents:
    words = document["text"].split()
    start = 0

    while start < len(words):
        end = start + CHUNK_SIZE
        chunk_text = " ".join(words[start:end])

        if chunk_text.strip():
            chunks.append({
                "chunk_id": chunk_id,
                "text": chunk_text,
                "source": document["source"],
                "page": document["page"]
            })
            chunk_id += 1

        start += CHUNK_SIZE - CHUNK_OVERLAP

print("✅ Chunking complete")
print("Total chunks:", len(chunks))

for chunk in chunks[:3]:
    print("=" * 60)
    print("CHUNK:", chunk["chunk_id"])
    print("SOURCE:", chunk["source"])
    print("PAGE:", chunk["page"])
    print("TEXT:", chunk["text"][:400])

"""# 5. Embeddings

An **embedding** converts text into a numerical vector representing its meaning.

We use the free local model:

`all-MiniLM-L6-v2`

So every chunk can be compared with an employee question without an API call.
"""

from sentence_transformers import SentenceTransformer

embedding_model = SentenceTransformer("all-MiniLM-L6-v2")

texts = [chunk["text"] for chunk in chunks]

embeddings = embedding_model.encode(
    texts,
    show_progress_bar=True
)

print("✅ Embeddings created")
print("Number of vectors:", len(embeddings))
print("Vector dimensions:", len(embeddings[0]))

"""# 6. Vector Database

We need to store:

- chunks
- embeddings
- metadata

We use **ChromaDB**, a local vector database.

Production systems can use PostgreSQL + pgvector or another vector database.
"""

!pip install -q chromadb
import chromadb

chroma_client = chromadb.Client()

collection = chroma_client.get_or_create_collection(
    name="hr_knowledge"
)

collection.add(
    ids=[str(chunk["chunk_id"]) for chunk in chunks],
    documents=texts,
    embeddings=embeddings.tolist(),
    metadatas=[
        {
            "source": chunk["source"],
            "page": chunk["page"]
        }
        for chunk in chunks
    ]
)

print("✅ Vector database ready")
print("Stored chunks:", collection.count())

"""# 7. Ask a Natural-Language Question

Now we move to the query side.

Example:

> How many days of annual leave can I take?

The question will also be converted into an embedding.
"""

question = input("Ask an HR question: ")

query_embedding = embedding_model.encode(
    [question]
)[0].tolist()

print("\nQUESTION:", question)
print("✅ Query embedding created")

"""# 8. Similarity Search + Semantic Search

**Similarity Search:** find vectors closest to the question vector.

**Semantic Search:** because embeddings represent meaning, relevant text can be found even when the exact words differ.

We retrieve the Top-K most relevant chunks.
"""

results = collection.query(
    query_embeddings=[query_embedding],
    n_results=min(3, len(chunks))
)

print("✅ Similarity search complete")

retrieved_chunks = []

for i, text in enumerate(results["documents"][0]):
    metadata = results["metadatas"][0][i]
    distance = results["distances"][0][i]

    item = {
        "text": text,
        "source": metadata["source"],
        "page": metadata["page"],
        "distance": distance
    }

    retrieved_chunks.append(item)

    print("=" * 60)
    print("RANK:", i + 1)
    print("DISTANCE:", round(distance, 4))
    print("SOURCE:", metadata["source"])
    print("PAGE:", metadata["page"])
    print("TEXT:", text[:700])

"""# 9. Retrieval

This is the **Retrieval** part of RAG.

```text
Employee Question
       ↓
Query Embedding
       ↓
Similarity Search
       ↓
Top-K Relevant Chunks
```

The system has found evidence before generating an answer.

# 10. Augmentation

Now we put the retrieved evidence into a prompt.

This is the **Augmentation** part of RAG.

The language model will receive:

1. The employee's question
2. The retrieved company policy information
"""

context = "\n\n".join(
    f"SOURCE: {chunk['source']}\n"
    f"PAGE: {chunk['page']}\n"
    f"CONTENT: {chunk['text']}"
    for chunk in retrieved_chunks
)

prompt = (
    "You are a productivity agent.\n\n"
    "Answer the question using ONLY the company policy context. "
    "Do not invent policies.\n\n"
    "QUESTION:\n" + question + "\n\n"
    "COMPANY POLICY CONTEXT:\n" + context
)

print("✅ RAG prompt created")
print(prompt[:3500])

"""# 11. Generation — Local LLM

Now we perform **Generation**.

We use a small instruction-following model locally in Colab.

If available, use a GPU:

**Runtime → Change runtime type → T4 GPU**

This keeps the practical free of API charges.
"""

import torch
from transformers import AutoTokenizer, AutoModelForCausalLM

MODEL_NAME = "Qwen/Qwen2.5-0.5B-Instruct"

device = "cuda" if torch.cuda.is_available() else "cpu"

print("Loading local LLM on:", device)

tokenizer = AutoTokenizer.from_pretrained(MODEL_NAME)

model = AutoModelForCausalLM.from_pretrained(
    MODEL_NAME,
    torch_dtype=torch.float16 if device == "cuda" else torch.float32
)

model = model.to(device)
model.eval()

print("✅ Local LLM loaded")

if 'tokenizer' not in globals() or 'model' not in globals():
    import torch
    from transformers import AutoTokenizer, AutoModelForCausalLM

    MODEL_NAME = "Qwen/Qwen2.5-0.5B-Instruct"
    device = "cuda" if torch.cuda.is_available() else "cpu"

    print("Re-loading local LLM components due to NameError...")
    tokenizer = AutoTokenizer.from_pretrained(MODEL_NAME)
    model = AutoModelForCausalLM.from_pretrained(
        MODEL_NAME,
        torch_dtype=torch.float16 if device == "cuda" else torch.float32
    )
    model = model.to(device)
    model.eval()
    print("✅ Local LLM components re-loaded")

messages = [
    {
        "role": "system",
        "content": "You are an HR policy assistant. Use only the supplied company context. Do not invent policies."
    },
    {
        "role": "user",
        "content": prompt
    }
]

formatted_prompt = tokenizer.apply_chat_template(
    messages,
    tokenize=False,
    add_generation_prompt=True
)

inputs = tokenizer(
    formatted_prompt,
    return_tensors="pt",
    truncation=True,
    max_length=4096
).to(device)

with torch.no_grad():
    output = model.generate(
        **inputs,
        max_new_tokens=250,
        do_sample=False
    )

new_tokens = output[0][inputs["input_ids"].shape[1]:]

answer = tokenizer.decode(
    new_tokens,
    skip_special_tokens=True
)

print("ANSWER")
print("=" * 60)
print(answer)

"""# 12. Citations

Because we kept `source` and `page` as metadata, we can show where the retrieved evidence came from.

This gives the user a **source-backed answer**.
"""

print("SOURCES USED")
print("-" * 50)

seen = set()

for chunk in retrieved_chunks:
    citation = (chunk["source"], chunk["page"])

    if citation not in seen:
        print(f"• {chunk['source']} — Page {chunk['page']}")
        seen.add(citation)

"""# 13. Multi-Document Search

All uploaded PDFs are stored in the same vector database.

Therefore one employee question can search across:

```text
Leave Policy
Work From Home Policy
Employee Handbook
Travel Policy
        ↓
   One Vector DB
        ↓
Relevant chunks
```

Try questions about different policies and observe the source documents returned.
"""

print("Documents in the knowledge base:")

for source in sorted(set(chunk["source"] for chunk in chunks)):
    print(" -", source)

print("\nTotal searchable chunks:", collection.count())

"""# 14. Evaluation

A RAG system must be evaluated.

### Retrieval
Did we retrieve the correct chunks?

### Answer
Did the answer correctly use those chunks?

### Groundedness
Are the answer's claims supported by the retrieved documents?

### Citation correctness
Does the cited document/page actually support the answer?
"""

print("Retrieved evidence for evaluation:")
for rank, chunk in enumerate(retrieved_chunks, start=1):
    print(
        f"{rank}. {chunk['source']} | "
        f"Page {chunk['page']} | "
        f"distance={chunk['distance']:.4f}"
    )

"""# 15. Final RAG Pipeline

```text
PDFs
 ↓
Text Extraction
 ↓
Chunking
 ↓
Metadata
 ↓
Embeddings
 ↓
Vector Database
 ↓
User Question
 ↓
Query Embedding
 ↓
Similarity / Semantic Search
 ↓
Relevant Chunks
 ↓
Augmented Prompt
 ↓
LLM Generation
 ↓
Source-backed Answer
 ↓
Citations
```

## Syllabus coverage

- ✅ Embeddings
- ✅ Vector Databases
- ✅ Semantic Search
- ✅ Chunking Strategies
- ✅ Metadata
- ✅ Similarity Search
- ✅ RAG Pipelines
- ✅ Evaluation

## Hands-on features

- ✅ Upload PDFs
- ✅ Ask natural-language questions
- ✅ Source-backed answers
- ✅ View citations
- ✅ Multi-document search

## Industry Challenge

**HR policy assistant capable of answering employee queries using company documents.**
"""